### ISSUE TITLE
[sensorlib] CARLA CDASim adapter example uses outdated API

### ISSUE THREAD

**Issue by adamlm** [usdot-fhwa-stol/carma-utils#161]
### Summary

The Java example for interacting with the CARLA CDASim adapter uses an outdated API. It should be updated to reflect the new usage. The problematic code is in the `CarlaCDASimAdapter.md` file.

### Commit

`develop`

### Expected Behavior

Following the example should not result in errors.

### Actual Behavior

Following the example code produces errors because the function signatures are wrong.

### Steps to Reproduce the Actual Behavior

Attempt to run the example Java code.

### Related Work

[CDAR-473](https://usdot-carma.atlassian.net/browse/CDAR-473)

[CDAR-473]: https://usdot-carma.atlassian.net/browse/CDAR-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by MishkaMN** [comment]
Latest commit at 70797645c9d54927ead8cf3ef662453cb9741a26 was confirmed that this is resolved
